export const algorithmCatalog = {
  sorting: [
    {
      id: 'bubbleSort',
      name: 'Bubble Sort',
      tag: 'Sorting',
      accent: '#38bdf8',
      complexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)', space: 'O(1)' },
      summary: 'Compares adjacent values and repeatedly pushes larger values to the right.',
    },
    {
      id: 'selectionSort',
      name: 'Selection Sort',
      tag: 'Sorting',
      accent: '#f97316',
      complexity: { best: 'O(n²)', average: 'O(n²)', worst: 'O(n²)', space: 'O(1)' },
      summary: 'Scans for the next minimum value and places it into the sorted prefix.',
    },
    {
      id: 'insertionSort',
      name: 'Insertion Sort',
      tag: 'Sorting',
      accent: '#22c55e',
      complexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)', space: 'O(1)' },
      summary: 'Builds a sorted section one item at a time by shifting larger values.',
    },
    {
      id: 'mergeSort',
      name: 'Merge Sort',
      tag: 'Sorting',
      accent: '#a855f7',
      complexity: {
        best: 'O(n log n)',
        average: 'O(n log n)',
        worst: 'O(n log n)',
        space: 'O(n)',
      },
      summary: 'Splits the array, sorts each half, then merges ordered ranges back together.',
    },
    {
      id: 'quickSort',
      name: 'Quick Sort',
      tag: 'Sorting',
      accent: '#f43f5e',
      complexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n²)', space: 'O(log n)' },
      summary: 'Partitions values around a pivot and recursively sorts the resulting regions.',
    },
  ],
  graph: [
    {
      id: 'bfs',
      name: 'Breadth-First Search',
      tag: 'Graph',
      accent: '#06b6d4',
      complexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)', space: 'O(V)' },
      summary: 'Explores neighbors level by level using a queue, ideal for shortest unweighted paths.',
    },
    {
      id: 'dfs',
      name: 'Depth-First Search',
      tag: 'Graph',
      accent: '#84cc16',
      complexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)', space: 'O(V)' },
      summary: 'Follows one branch deeply before backtracking through the graph.',
    },
    {
      id: 'dijkstra',
      name: "Dijkstra's Algorithm",
      tag: 'Graph',
      accent: '#facc15',
      complexity: {
        best: 'O((V + E) log V)',
        average: 'O((V + E) log V)',
        worst: 'O((V + E) log V)',
        space: 'O(V)',
      },
      summary: 'Relaxes weighted edges to find the lowest-cost paths from a source node.',
    },
  ],
}
