export const algorithmCatalog = {
  sorting: [
    {
      id: 'bubbleSort',
      name: 'Bubble Sort',
      tag: 'Sorting',
      accent: '#38bdf8',
      complexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)', space: 'O(1)' },
      summary: 'Compares adjacent values and repeatedly pushes larger values to the right.',
    },
    {
      id: 'selectionSort',
      name: 'Selection Sort',
      tag: 'Sorting',
      accent: '#f97316',
      complexity: { best: 'O(n²)', average: 'O(n²)', worst: 'O(n²)', space: 'O(1)' },
      summary: 'Scans for the next minimum value and places it into the sorted prefix.',
    },
    {
      id: 'insertionSort',
      name: 'Insertion Sort',
      tag: 'Sorting',
      accent: '#22c55e',
      complexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)', space: 'O(1)' },
      summary: 'Builds a sorted section one item at a time by shifting larger values.',
    },
    {
      id: 'mergeSort',
      name: 'Merge Sort',
      tag: 'Sorting',
      accent: '#a855f7',
      complexity: {
        best: 'O(n log n)',
        average: 'O(n log n)',
        worst: 'O(n log n)',
        space: 'O(n)',
      },
      summary: 'Splits the array, sorts each half, then merges ordered ranges back together.',
    },
    {
      id: 'quickSort',
      name: 'Quick Sort',
      tag: 'Sorting',
      accent: '#f43f5e',
      complexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n²)', space: 'O(log n)' },
      summary: 'Partitions values around a pivot and recursively sorts the resulting regions.',
    },
  ],
  graph: [
    {
      id: 'bfs',
      name: 'Breadth-First Search',
      tag: 'Graph',
      accent: '#06b6d4',
      complexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)', space: 'O(V)' },
      summary: 'Explores neighbors level by level using a queue, ideal for shortest unweighted paths.',
    },
    {
      id: 'dfs',
      name: 'Depth-First Search',
      tag: 'Graph',
      accent: '#84cc16',
      complexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)', space: 'O(V)' },
      summary: 'Follows one branch deeply before backtracking through the graph.',
    },
    {
      id: 'dijkstra',
      name: "Dijkstra's Algorithm",
      tag: 'Graph',
      accent: '#facc15',
      complexity: {
        best: 'O((V + E) log V)',
        average: 'O((V + E) log V)',
        worst: 'O((V + E) log V)',
        space: 'O(V)',
      },
      summary: 'Relaxes weighted edges to find the lowest-cost paths from a source node.',
    },
  ],
  searching: [
    {
      id: 'linearSearch',
      name: 'Linear Search',
      tag: 'Searching',
      accent: '#ec4899',
      complexity: { best: 'O(1)', average: 'O(n)', worst: 'O(n)', space: 'O(1)' },
      summary: 'Scans each element sequentially until the target is found or the array ends.',
    },
    {
      id: 'binarySearch',
      name: 'Binary Search',
      tag: 'Searching',
      accent: '#14b8a6',
      complexity: { best: 'O(1)', average: 'O(log n)', worst: 'O(log n)', space: 'O(1)' },
      summary: 'Repeatedly divides a sorted array in half, narrowing the search range.',
    },
  ],
  trees: [
    {
      id: 'bstInsert',
      name: 'BST Insertion',
      tag: 'Trees',
      accent: '#8b5cf6',
      complexity: { best: 'O(log n)', average: 'O(log n)', worst: 'O(n)', space: 'O(n)' },
      summary: 'Inserts values into a Binary Search Tree, preserving the ordered structure.',
    },
    {
      id: 'bstSearch',
      name: 'BST Search',
      tag: 'Trees',
      accent: '#d946ef',
      complexity: { best: 'O(1)', average: 'O(log n)', worst: 'O(n)', space: 'O(1)' },
      summary: 'Traverses the BST to locate a target value by comparing at each node.',
    },
    {
      id: 'inorderTraversal',
      name: 'Inorder Traversal',
      tag: 'Trees',
      accent: '#f59e0b',
      complexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)', space: 'O(n)' },
      summary: 'Visits nodes in left-root-right order, producing sorted output from a BST.',
    },
    {
      id: 'preorderTraversal',
      name: 'Preorder Traversal',
      tag: 'Trees',
      accent: '#10b981',
      complexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)', space: 'O(n)' },
      summary: 'Visits nodes in root-left-right order, useful for copying the tree.',
    },
    {
      id: 'postorderTraversal',
      name: 'Postorder Traversal',
      tag: 'Trees',
      accent: '#ef4444',
      complexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)', space: 'O(n)' },
      summary: 'Visits nodes in left-right-root order, useful for deleting the tree.',
    },
  ],
  dp: [
    {
      id: 'fibonacci',
      name: 'Fibonacci',
      tag: 'DP',
      accent: '#3b82f6',
      complexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)', space: 'O(n)' },
      summary: 'Computes the nth Fibonacci number using bottom-up dynamic programming.',
    },
    {
      id: 'gridTraveler',
      name: 'Grid Traveler',
      tag: 'DP',
      accent: '#84cc16',
      complexity: { best: 'O(m*n)', average: 'O(m*n)', worst: 'O(m*n)', space: 'O(m*n)' },
      summary: 'Counts unique paths from top-left to bottom-right in a grid moving only down or right.',
    },
  ],
  stackqueue: [
    {
      id: 'stackPush',
      name: 'Stack Push',
      tag: 'Stack/Queue',
      accent: '#f97316',
      complexity: { best: 'O(1)', average: 'O(1)', worst: 'O(1)', space: 'O(n)' },
      summary: 'Pushes a random value onto the top of the stack (LIFO).',
    },
    {
      id: 'stackPop',
      name: 'Stack Pop',
      tag: 'Stack/Queue',
      accent: '#dc2626',
      complexity: { best: 'O(1)', average: 'O(1)', worst: 'O(1)', space: 'O(1)' },
      summary: 'Removes and displays the top element from the stack.',
    },
    {
      id: 'queueEnqueue',
      name: 'Queue Enqueue',
      tag: 'Stack/Queue',
      accent: '#0891b2',
      complexity: { best: 'O(1)', average: 'O(1)', worst: 'O(1)', space: 'O(n)' },
      summary: 'Adds a random value to the rear of the queue (FIFO).',
    },
    {
      id: 'queueDequeue',
      name: 'Queue Dequeue',
      tag: 'Stack/Queue',
      accent: '#7c3aed',
      complexity: { best: 'O(1)', average: 'O(1)', worst: 'O(1)', space: 'O(1)' },
      summary: 'Removes and displays the front element from the queue.',
    },
  ],
}
